#!/usr/bin/env python3
"""Install the Draw.io Desktop CLI, which the `drawio` diagram renderer shells out to.

Root-free by design: the official Linux build ships only as an AppImage, so this unpacks one
into a user prefix and puts a wrapper on PATH. Re-running is safe and cheap.

Usage:
    python3 install_drawio.py [version] [--prefix DIR] [--bindir DIR]

Stdlib only -- this has to run before the skill's own requirements are installed.
"""
from __future__ import annotations

import argparse
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path
from typing import NoReturn

REPO = "jgraph/drawio-desktop"
USER_AGENT = "publish-page-install-drawio"
ARCHES = {"x86_64": "x86_64", "aarch64": "arm64", "arm64": "arm64"}
VERSION_PATTERN = re.compile(r"\A\d+(?:\.\d+)*\Z")

WRAPPER = """#!/usr/bin/env bash
# Draw.io Desktop CLI wrapper -- generated by publish-page/scripts/install_drawio.py
set -euo pipefail

# --no-sandbox: chrome-sandbox needs setuid root, which a user-prefix install cannot have.
# --disable-gpu: there is no GPU worth using for a batch export, and probing for one is noise.
set -- --no-sandbox --disable-gpu "$@"

# Electron needs an X display even to export; borrow a virtual one when there is no real one.
if [[ -z "${DISPLAY:-}" ]]; then
    if command -v xvfb-run >/dev/null; then
        exec xvfb-run -a "@APPRUN@" "$@"
    fi
    echo "error: drawio needs an X display; set DISPLAY or install xvfb (apt install xvfb)" >&2
    exit 1
fi
exec "@APPRUN@" "$@"
"""


def fail(message: str) -> NoReturn:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def detect_arch() -> str:
    machine = platform.machine()
    arch = ARCHES.get(machine)
    if not arch:
        fail(f"no Draw.io Desktop build for {machine}")
    return arch


def latest_version() -> str:
    print("Resolving the latest Draw.io Desktop release...")
    request = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}/releases/latest",
        headers={"User-Agent": USER_AGENT, "Accept": "application/vnd.github+json"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        tag = json.load(response).get("tag_name", "")
    version = tag.lstrip("v")
    if not version:
        fail("could not resolve the latest release")
    return version


def download(url: str, dest: Path) -> None:
    print(f"Downloading {url}")
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        response = urllib.request.urlopen(request, timeout=60)
    except urllib.error.HTTPError as exception:
        hint = " -- no such release for this version/architecture" if exception.code == 404 else ""
        fail(f"download failed: HTTP {exception.code}{hint}")
    with response, dest.open("wb") as out:
        total = int(response.headers.get("Content-Length") or 0)
        read = 0
        while chunk := response.read(1 << 20):
            out.write(chunk)
            read += len(chunk)
            done = f"{read / 1e6:.0f}MB"
            print(f"\r  {done} of {total / 1e6:.0f}MB" if total else f"\r  {done}", end="")
    print()


def extract(appimage: Path, prefix: Path) -> None:
    print(f"Unpacking into {prefix}")
    appimage.chmod(0o755)
    # Unpack rather than run the AppImage directly: extraction needs no FUSE and no root.
    subprocess.run(
        [str(appimage), "--appimage-extract"],
        cwd=appimage.parent,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    if prefix.exists():
        shutil.rmtree(prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)
    (appimage.parent / "squashfs-root").rename(prefix)


def write_wrapper(wrapper: Path, prefix: Path) -> None:
    wrapper.parent.mkdir(parents=True, exist_ok=True)
    wrapper.write_text(WRAPPER.replace("@APPRUN@", str(prefix / "AppRun")))
    wrapper.chmod(0o755)


def verify_mermaid_import(wrapper: Path, workdir: Path) -> None:
    print("Verifying the Mermaid import path...")
    source = workdir / "probe.mmd"
    source.write_text("graph TD;\n  A[Start] --> B[Done];\n")
    diagram = workdir / "probe.drawio"
    result = subprocess.run(
        [str(wrapper), "-x", "-f", "xml", "-u", "-o", str(diagram), str(source)],
        capture_output=True,
        text=True,
    )
    if not diagram.exists() or "mermaidId" not in diagram.read_text():
        detail = (result.stderr or result.stdout).strip().splitlines()
        tail = detail[-1] if detail else f"exit {result.returncode}"
        fail(f"drawio installed but did not import Mermaid into an editable diagram: {tail}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("version", nargs="?", help="version to pin (default: latest release)")
    parser.add_argument(
        "--prefix",
        type=Path,
        default=Path.home() / ".local" / "opt" / "drawio",
        help="where to unpack the AppImage",
    )
    parser.add_argument(
        "--bindir",
        type=Path,
        default=Path.home() / ".local" / "bin",
        help="where to put the `drawio` wrapper",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    arch = detect_arch()
    version = (args.version or latest_version()).lstrip("v")
    if not VERSION_PATTERN.match(version):
        fail(f"{version!r} is not a version number")

    wrapper = args.bindir / "drawio"
    stamp = args.prefix / ".version"
    if wrapper.exists() and stamp.exists() and stamp.read_text().strip() == version:
        print(f"Draw.io CLI {version} already installed at {wrapper}")
        return

    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        appimage = workdir / "drawio.AppImage"
        download(
            f"https://github.com/{REPO}/releases/download/v{version}/drawio-{arch}-{version}.AppImage",
            appimage,
        )
        extract(appimage, args.prefix)
        write_wrapper(wrapper, args.prefix)
        verify_mermaid_import(wrapper, workdir)

    stamp.write_text(f"{version}\n")
    print(f"Draw.io CLI {version} installed at {wrapper}")
    if str(args.bindir) not in os.environ.get("PATH", "").split(os.pathsep):
        print(
            f"warning: {args.bindir} is not on PATH; add it so /publish-page can find drawio",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
